feat: detect already used token
If user tries to register:
* when already logged in, redirect to /my/
* when invitation already processed, redirect to login

In order to fool psalm unused detection which is raising false-positive
UnevaluatedCode errors, calls to `$layout->redirect()` is extracted to
dedicated methods.

> ERROR: UnevaluatedCode - src/common/User/Account/Register/AfterSuccessfulUserRegistration.php:92:13 - Expressions after return/throw/continue (see https://psalm.dev/084)
>            return;

Part of request #29614: Invited users shouldn't be mandated to re-confirm their email

Change-Id: I6a6c079de10cba53f4ce8bcd879bedb28631acfe