request #14968 TLP modal should not crash when hidden before being shown
How to test:
- in src/ run "npm run build"
- Browse to a TestManagement campaign. Click on the "Edit campaign"
button. Click on "Add a test" button. A "Create artifact" modal should
open. Click on the "Cancel" button.
- You should not have a DOMException in the console: "Uncaught
DOMException: Node.removeChild: The node to be removed is not a child of
this node"
- The modal and its backdrop element are removed.

- Thanks to Babel transpilation, Internet Explorer 11 does not crash (it
does not support ChildNode.remove() DOM API).

- "make tests_cypress" should succeed on TestManagement e2e tests

Change-Id: Iadd191577172689017552690887722fdac766809