Import project icon
part of story #22687 distinguish projects with an icon

How to test
update rncrng with make rnc2rng-docker command

in a project add in xml an icon
example:
<project access="public" description="" full-name="Project administration test" unix-name="project-admin-test" icon-codepoint="😀">

Import your project:
 => the icon is displayed in project home page

Note:
An assertion have been added in cypress tests to be sure that icon import won't break

Note psalm:
I didn't manage to don't have breaking change with psalm, when I introduce `db_es` in `ProjectCreator` it makes psalm unhappy with:
ERROR: DeprecatedFunction - src/common/Project/ProjectCreator.class.php:758:19 - The function db_query has been marked as deprecated (see https://psalm.dev/201)


Change-Id: I51255f913b36841f0a11ca4dc10ef10327b9bbe7