request #9898 Javascript warning thrown
Go on tracker page for example, open console
TypeError: select_element is null[Learn More]

Change-Id: I8535707ffce5c74b06a1c216d0a1792a5740a972