fix: fatal error due to hidden dependency
We have this dependencies: AD -> Cardwall -> Tracker

However Cardwall depends on AD to provide its PaneInfo.

Since 64846e0d5e911cc0c1e0b05d42b71d3ab9343631, agiledashboard is not
always loaded, and we get a fatal error:

Fatal error: Uncaught Error: Class "Tuleap\AgileDashboard\Milestone\Pane\PaneInfo" not found in /usr/share/tuleap/plugins/cardwall/include/Cardwall/Agiledashboard/PaneInfo.php on line 26
Error: Class "Tuleap\AgileDashboard\Milestone\Pane\PaneInfo" not found in /usr/share/tuleap/plugins/cardwall/include/Cardwall/Agiledashboard/PaneInfo.php on line 26

In order to "solve" this, the PaneInfo is moved to the tracker plugin as
it is the only common dependency for all those plugins.

Part of request #25680: Decrease usage of BurningParrotCompatiblePageEvent

Change-Id: Ia8c7a58ceabea6f636585e1bb1691ab63c6023ff