Update of global timeout to decrease cypress failures
this is part of request #11328 move some TTM tests to cypress

Most of cypress failures are due to following error:
CypressError: Timed out after waiting '60000ms' for your remote page to load.

This commit update the global timeout to see if we have less errors

Change-Id: I66a66a748811fbf372e72e79fa62fbabcc5bd3db