fixes request #42178 tracker reminder can end in fatal error when notification is set over role
How to reproduce:
Add a notification reminder over a `role` and not a `user_group`

A fatal error is thrown:
Fatal error: Uncaught TypeError: UGroupDao::searchByUGroupId(): Argument #1 ($ugroup_id) must be of type int, string given, called in /usr/share/tuleap/src/common/Project/UGroupManager.php on line 319 and defined in /usr/share/tuleap/src/common/dao/UGroupDao.php:30 Stack trace: #0 /usr/share/tuleap/src/common/Project/UGroupManager.php(319): UGroupDao->searchByUGroupId() #1 /usr/share/tuleap/plugins/tracker/include/Tracker/DateReminder/Tracker_DateReminder.php(350): UGroupManager->getById() #2 /usr/share/tuleap/plugins/tracker/include/Tracker/DateReminder/Tracker_DateReminderRenderer.php(476): Tracker_DateReminder->getUgroupsLabel() #3 /usr/share/tuleap/plugins/tracker/include/Tracker/DateReminder/Tracker_DateReminderRenderer.php(538): Tracker_DateReminderRenderer->displayAllReminders() #4 /usr/share/tuleap/plugins/tracker/include/Tracker/Tracker_NotificationsManager.php(130): Tracker_DateReminderRenderer->displayDateReminders() #5 /usr/share/tuleap/plugins/tracker/include/Tracker/Notifications/Settings/Administration/NotificationsAdminSettingsDisplayController.php(75): Tracker_NotificationsManager->displayTrackerAdministratorSettings() #6 /usr/share/tuleap/src/common/Request/FrontRouter.php(251): Tuleap\Tracker\Notifications\Settings\NotificationsAdminSettingsDisplayController->process() #7 /usr/share/tuleap/src/common/Request/FrontRouter.php(109): Tuleap\Request\FrontRouter->routeHandler() #8 /usr/share/tuleap/src/www/index.php(50): Tuleap\Request\FrontRouter->route() #9 {main} thrown in /usr/share/tuleap/src/common/dao/UGroupDao.php on line 30

No error with this patch

Change-Id: I64798319c9632dd09172e17736e8b1c4c3168f74