Correct error in BacklogItemPresenter
part of request #41438 Fix psalm issues in AgileDashboard plugin

In backlog when task list of story is loaded a fatal error is thrown

Fatal error: Uncaught Error: Typed property Tuleap\AgileDashboard\Milestone\Backlog\BacklogItem::$normalized_status_label must not be accessed before initialization in /usr/share/tuleap/plugins/agiledashboard/include/AgileDashboard/Milestone/Backlog/BacklogItem.php:152 Stack trace: #0 /usr/share/tuleap/plugins/agiledashboard/include/AgileDashboard/REST/v1/BacklogItemRepresentation.php(82):

Introduced by I8f9443fd65676f2270df72f95e7eb9839ee1b658

Change-Id: Ia216860438946346b4044abedcb15baf3be6409f