Implement tus protocol for Tracker REST API
First step to be able to attach files to an artifact with tus.

How to test
-----------
To test you can use the following snippet. You will have to provide the
path to the tus.js client library and update the field id to match
your environment. Upload information (progress) is displayed on the
devtools console. When the upload is done you can assert that the file
is present (and identical to the uploaded one) in the filesystem under
/var/lib/tuleap/tracker/<field_id>.

```
<input type="file" id="myfile">
<script src="tus.js"></script>
<script>
document.getElementById('myfile').addEventListener('change', async (e) => {
    const field_id = 94;

    const file = e.target.files[0];

    const post_response = await fetch(`/api/v1/tracker_fields/${field_id}/files`, {
        method: 'POST',
        credentials: 'same-origin',
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            name: file.name,
            file_size: file.size,
            file_type: file.type
        })
    });
    const post_response_body = await post_response.json();
    const upload_href = post_response_body["upload_href"];

    // Create a new tus upload
    const upload = new tus.Upload(file, {
        uploadUrl: upload_href,
        retryDelays: [0, 3000, 5000],
        metadata: {
            filename: file.name,
            filetype: file.type
        },
        onError: function(error) {
            console.log("Failed because: " + error);
        },
        onProgress: function(bytesUploaded, bytesTotal) {
            const percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
            console.log(bytesUploaded, bytesTotal, percentage + "%");
        },
        onSuccess: function() {
            console.log(" %s uploaded to %s", upload.file.name, upload.url);
            alert('Done');
        }
    });

    // Start the upload
    upload.start();
});
</script>
```

Part of story #12964: drag'n drop images in tracker text areas

Change-Id: I244c0dc6d11b2d8dec124e5e0fd80b591fec497c