request #34741 add missing intercept in testmanagment query
Found in nightly, tests might end with following statement:
AssertionError: Timed out retrying after 4000ms: Expected to find content: 'My first test edited' within the element: <h1.current-test-header-title.ng-binding> but never did. at Context.eval (webpack:///./cypress/e2e/campaign.cy.ts:141:0)

Change-Id: Id85dc4935e06ecbcb5cbbc5b46ede7b15170fcc2