fix: disable code coverage for artidoc
Since introduction of ckeditor at 489410e93ff7ed08ec74c6f150719e1a787634a7
The nightly tests are failing because an error is raised during the code
coverage:

COLLECT_COVERAGE=true CI_MODE="true" pnpm --filter=plugin-artidoc test
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
SyntaxError: Unexpected token '�', "���rب�+h��n�" is not valid JSON
 ❯ new Converter ../../../../node_modules/.pnpm/convert-source-map@2.0.0/node_modules/convert-source-map/index.js:83:15
 ❯ exports.fromComment ../../../../node_modules/.pnpm/convert-source-map@2.0.0/node_modules/convert-source-map/index.js:181:10
 ❯ exports.fromSource ../../../../node_modules/.pnpm/convert-source-map@2.0.0/node_modules/convert-source-map/index.js:207:22
 ❯ V8ToIstanbul.load ../../../../node_modules/.pnpm/v8-to-istanbul@9.2.0/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:53:24
 ❯ ../../../../node_modules/.pnpm/@vitest+coverage-v8@1.0.4_vitest@1.0.4/node_modules/@vitest/coverage-v8/dist/provider.js:392:25
 ❯ V8CoverageProvider.convertCoverage ../../../../node_modules/.pnpm/@vitest+coverage-v8@1.0.4_vitest@1.0.4/node_modules/@vitest/coverage-v8/dist/provider.js:388:7
 ❯ V8CoverageProvider.reportCoverage ../../../../node_modules/.pnpm/@vitest+coverage-v8@1.0.4_vitest@1.0.4/node_modules/@vitest/coverage-v8/dist/provider.js:273:25
 ❯ Vitest.reportCoverage ../../../../node_modules/.pnpm/vitest@1.0.4_jsdom@23.0.1_sass@1.71.1/node_modules/vitest/dist/vendor/node.vEetZgP7.js:8325:7

```

I didn't find any way to exclude only the file
`plugins/artidoc/scripts/artidoc/src/components/SectionDescriptionEditor.vue`
that is causing issue from the coverage report, so I choose to disable
completely coverage for artidoc app.

This will give us some time to find a better solution.

Part of story #37543: edit Artidoc sections

Change-Id: I154f415ffd8c33c8d7282e13009759c4b64a43ef