Fix unused code detection
part of request #31562: Always run Psalm unused code detection

Psalm trigger following error:
ERROR: UnusedDocblockParam - tests/unit/common/WebAuthn/Controllers/PostRegistrationChallengeControllerTest.php:136:24 - Docblock parameter $sources_id in docblock for Tuleap\WebAuthn\Controllers\PostRegistrationChallengeControllerTest::getController does not have a counterpart in signature parameter list (see https://psalm.dev/319)
    /**
     * @param string[] $sources_id
     */
    private function getController(

Change-Id: I08942c18ce438c98ca7b59ef832d823c66d069d6