Correct unused private field
part of request #22583 Add missing configuration errors in program admin section

Detected by nightly:
ERROR: UnusedProperty - plugins/program_management/include/Domain/Program/Admin/Configuration/RequiredErrorPresenter.php:39:21 - Cannot find explicit references to private property Tuleap\ProgramManagement\Domain\Program\Admin\Configuration\RequiredErrorPresenter::$field_id (but did find some potential references) (see https://psalm.dev/150)
private int $field_id,

Change-Id: I818ca1fbc7dbeb2c6c116dc81e284872763d8f01