request #25357 Improve re-playability of SVN plugin e2e tests
make tests-e2e should succeed for SVN plugin test (you can edit
tests/e2e/full/run.sh to only run svn plugin tests)

Notes:
I tried to improve general re-playability but there is still one
exception: deletion of svn repo. In this case, we have to wait for the
system event to finish creation of the repo before being able to delete
it. This means I cannot delete the repo that has just been created (in
the "create repo" test). That means I can only delete the repo that is
imported from XML, so this test can only run once. Ideas are welcome to
improve this.

Change-Id: Iabf56419f71975b54ad353a9c7a55e7d2fcd43a3