closes request #28890 fix unused spotted by static analysis
ERROR: UnusedProperty - plugins/gitlab/include/API/GitlabRequestFault.php:32:49 - Cannot find explicit references to private property Tuleap\Gitlab\API\GitlabRequestFault::$message (but did find some potential references) (see https://psalm.dev/150)

    private function __construct(private string $message, private int $status_code)

ERROR: UnusedProperty - plugins/tracker/include/Tracker/Semantic/Status/Done/SemanticDoneAdminPresenter.php:37:25 - Cannot find explicit references to private property Tuleap\Tracker\Semantic\Status\Done\SemanticDoneAdminPresenter::$tracker (but did find some potential references) (see https://psalm.dev/150)

        private Tracker $tracker,

Change-Id: I00d4b2190d4f12c29162fb8da91352e0978e9880