Remove unused variable RetrieveUser
part of request #23043 Program management: clean domain

Spotted by psalm
ERROR: UnusedProperty - plugins/program_management/include/DisplayAdminProgramManagementController.php:94:30 - Cannot find any references to private property Tuleap\ProgramManagement\DisplayAdminProgramManagementController::$retrieve_user (see https://psalm.dev/150)
private RetrieveUser $retrieve_user

Change-Id: I6197c3f119af85b5b6bafb304a3bc0d35ba67e18