Fatal error when adding a new chart in a tracker report
Issue was introduced by d32f105fdd38e818dd03698bc2200f8885626861.

When adding a new chart in a tracker report a fatal error is thrown:
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function GraphOnTrackersV5_Chart::getContent(), 0 passed in /usr/share/tuleap/plugins/graphontrackersv5/include/GraphOnTrackersV5_Renderer.class.php on line 120 and exactly 1 expected in /usr/share/tuleap/plugins/graphontrackersv5/include/data-access/GraphOnTrackersV5_Chart.class.php on line 608
```

Part of request #23821: Widget reports shouldn't be based on session reports

Change-Id: I7d919fef3c4c63b8403bee07a2dbffce942813f9