Revert commit b89ac860206a7d0e43f79b06ebafc71e53d0001d
It throws error when accessing API:
Fatal error: Exception thrown without a stack frame in Unknown on line <i>0</i>

Change-Id: Iad7d0f24656e0314fc23f4e0641209e95cad0892