request #22704 Fatal error when semantic status is no longer defined
How to reproduce:
Have a Release tracker without a Semantic status defined Have the plugin Velocity enabled
(velocity is displayed only for top level trackers)

In tracker semantic administration, a fatal error is raised:

 Fatal error: Uncaught Error: Call to a member function isMultiple() on null in /usr/share/tuleap/plugins/velocity/include/Velocity/Semantic/SemanticVelocityPresenterBuilder.php on line 74
( ! ) Error: Call to a member function isMultiple() on null in /usr/share/tuleap/plugins/velocity/include/Velocity/Semantic/SemanticVelocityPresenterBuilder.php on line 74

Change-Id: I8f0baf19442338c7c354e5423bd2338630fc75d8