When program has no team, no js error should be thrown
story #21793 configure Program Management

On empty state
Error: admin-configuration-program-increment-tracker element does not exist
should not be thrown

RemoveError: admin-configuration-program-increment-tracker element does not exist
Change-Id: I3b6187bcd93e07ee394fd2e76ac9ac49fe1928a4