Correct fetchRawValueFromChangeset exception
part of request #41438 Fix psalm issues in AgileDashboard plugin

Note:
I did not manage to reproduce issue on my side, even ith faulty tracker
it seems that some value is null in db

Intorduce by
4f09cabfafe3a739399e2dc8bb118a2b5281e6fe

StackTrace:
Fatal error: Uncaught TypeError: Tracker_FormElement_Field_Alphanum::fetchRawValueFromChangeset(): Return value must be of type string, null returned in /usr/share/tuleap/plugins/tracker/include/Tracker/FormElement/Tracker_FormElement_Field_Alphanum.php:100 Stack trace: #0 /usr/share/tuleap/plugins/graphontrackersv5/include/DataTransformation/GraphOnTrackersV5_Chart_GanttDataBuilder.php(98): Tracker_FormElement_Field_Alphanum->fetchRawValueFromChangeset() #1 /usr/share/tuleap/plugins/graphontrackersv5/include/DataTransformation/GraphOnTrackersV5_Chart_GanttDataBuilder.php(45): Tuleap\GraphOnTrackersV5\DataTransformation\GraphOnTrackersV5_Chart_GanttDataBuilder->buildData() #2 /usr/share/tuleap/plugins/graphontrackersv5/include/DataAccess/GraphOnTrackersV5_Chart.php(471): Tuleap\GraphOnTrackersV5\DataTransformation\GraphOnTrackersV5_Chart_GanttDataBuilder->buildProperties() #3 /usr/share/tuleap/plugins/graphontrackersv5/include/DataAccess/GraphOnTrackersV5_Chart.php(443): Tuleap\GraphOnTrackersV5\DataAccess\GraphOnTrackersV5_Chart->getEngineWithData() #4

Change-Id: I079095784fa493e2c3b6b7ba7f7167377c106483